import { DashboardData } from './types';

export const mockData: DashboardData = {
  feedback: [
    {
      id: 'f1',
      username: 'sarah.dev',
      avatar: 'SD',
      content: 'HabitOS is great but I NEED dark mode! My eyes are begging you 🙏',
      timestamp: '2m ago',
      status: 'clustered',
      threadId: 'thread_1',
    },
    {
      id: 'f2',
      username: 'mike.codes',
      avatar: 'MC',
      content: 'Dark mode would be a game changer for late night coding sessions',
      timestamp: '5m ago',
      status: 'clustered',
      threadId: 'thread_1',
    },
    {
      id: 'f3',
      username: 'julia.fyi',
      avatar: 'JF',
      content: '+1 for dark mode. Every modern app needs it.',
      timestamp: '8m ago',
      status: 'clustered',
      threadId: 'thread_1',
    },
    {
      id: 'f4',
      username: 'alex.builds',
      avatar: 'AB',
      content: 'Can we get API key rotation? Current setup is insecure for teams',
      timestamp: '12m ago',
      status: 'new',
      threadId: 'thread_1',
    },
    {
      id: 'f5',
      username: 'priya.tech',
      avatar: 'PT',
      content: 'Export to CSV would save me hours of manual work every week',
      timestamp: '15m ago',
      status: 'new',
      threadId: 'thread_1',
    },
    {
      id: 'f6',
      username: 'dev.ninja',
      avatar: 'DN',
      content: 'The onboarding flow is confusing. Took me 20 min to find settings',
      timestamp: '18m ago',
      status: 'new',
      threadId: 'thread_1',
    },
    {
      id: 'f7',
      username: 'emma.writes',
      avatar: 'EW',
      content: 'Please add bulk edit! Managing 100+ items individually is painful',
      timestamp: '22m ago',
      status: 'new',
      threadId: 'thread_1',
    },
    {
      id: 'f8',
      username: 'ryan.stack',
      avatar: 'RS',
      content: 'Dark mode. That is all.',
      timestamp: '25m ago',
      status: 'clustered',
      threadId: 'thread_1',
    },
  ],
  requests: [
    {
      id: 'r1',
      title: 'Dark Mode Support',
      description: 'Add system-wide dark mode with automatic detection of user preference and manual toggle.',
      feedbackCount: 4,
      demandScore: 92,
      status: 'pending',
      feedbackSamples: [
        'Would love dark mode support! My eyes are begging you 🙏',
        'Dark mode would be a game changer for late night coding sessions',
        '+1 for dark mode. Every modern app needs it.',
      ],
      clusterId: 'cluster_dark_mode',
      createdAt: '2026-01-10T08:00:00Z',
    },
    {
      id: 'r2',
      title: 'API Key Rotation',
      description: 'Implement automatic API key rotation with configurable intervals and seamless key transitions.',
      feedbackCount: 1,
      demandScore: 45,
      status: 'pending',
      feedbackSamples: [
        'Can we get API key rotation? Current setup is insecure for teams',
      ],
      clusterId: 'cluster_api_rotation',
      createdAt: '2026-01-10T08:12:00Z',
    },
    {
      id: 'r3',
      title: 'CSV Export',
      description: 'Add one-click CSV export for all data views with column customization and date range filters.',
      feedbackCount: 1,
      demandScore: 38,
      status: 'pending',
      feedbackSamples: [
        'Export to CSV would save me hours of manual work every week',
      ],
      clusterId: 'cluster_csv_export',
      createdAt: '2026-01-10T08:15:00Z',
    },
    {
      id: 'r4',
      title: 'Improved Onboarding',
      description: 'Redesign the onboarding flow with interactive walkthroughs and contextual tooltips.',
      feedbackCount: 1,
      demandScore: 31,
      status: 'pending',
      feedbackSamples: [
        'The onboarding flow is confusing. Took me 20 min to find settings',
      ],
      clusterId: 'cluster_onboarding',
      createdAt: '2026-01-10T08:18:00Z',
    },
    {
      id: 'r5',
      title: 'Bulk Edit',
      description: 'Enable multi-select and bulk editing for all list views with undo/redo support.',
      feedbackCount: 1,
      demandScore: 28,
      status: 'pending',
      feedbackSamples: [
        'Please add bulk edit! Managing 100+ items individually is painful',
      ],
      clusterId: 'cluster_bulk_edit',
      createdAt: '2026-01-10T08:22:00Z',
    },
  ],
  pullRequests: [
    {
      id: 'pr1',
      requestId: 'r_dashboard',
      title: 'feat: Add interactive analytics dashboard',
      branch: 'feat/analytics-dashboard',
      repo: 'habitos',
      status: 'testing',
      currentStep: 'test_execution',
      completedSteps: ['repo_analysis', 'implementation_plan', 'code_generation', 'test_creation'],
      issueUrl: 'https://github.com/habitos/habitos/issues/42',
      prUrl: null,
      diffStats: {
        additions: 847,
        deletions: 23,
        filesChanged: 14,
      },
      testResults: {
        passed: 28,
        failed: 2,
        total: 30,
      },
      createdAt: '2026-01-10T07:45:00Z',
    },
    {
      id: 'pr2',
      requestId: 'r_search',
      title: 'perf: Optimize full-text search indexing',
      branch: 'perf/search-optimization',
      repo: 'habitos',
      status: 'ready',
      currentStep: 'pr_creation',
      completedSteps: [
        'repo_analysis',
        'implementation_plan',
        'code_generation',
        'test_creation',
        'test_execution',
      ],
      issueUrl: 'https://github.com/habitos/habitos/issues/38',
      prUrl: 'https://github.com/habitos/habitos/pull/67',
      diffStats: {
        additions: 312,
        deletions: 89,
        filesChanged: 7,
      },
      testResults: {
        passed: 45,
        failed: 0,
        total: 45,
      },
      createdAt: '2026-01-10T07:15:00Z',
    },
    {
      id: 'pr3',
      requestId: 'r_auth',
      title: 'feat: Add OAuth provider for GitHub',
      branch: 'feat/github-oauth',
      repo: 'habitos/auth-service',
      status: 'implementing',
      currentStep: 'code_generation',
      completedSteps: ['repo_analysis', 'implementation_plan'],
      issueUrl: 'https://github.com/habitos/auth-service/issues/15',
      prUrl: null,
      diffStats: {
        additions: 0,
        deletions: 0,
        filesChanged: 0,
      },
      testResults: {
        passed: 0,
        failed: 0,
        total: 0,
      },
      createdAt: '2026-01-10T08:00:00Z',
    },
  ],
};
